name: Custom Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run step
        run: echo "Hello from custom workflow"
